version: '3'
services:
  test:
    container_name: test:0.1
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - '6464:6464'
